export const booksData = [
    {
      bookName: "The Power of Habit",
      category: "self help",
      publisher: "Random House",
      wantToRead: true,
      alreadyRead: false,
      currentlyReading: false,
      image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"
    },
    {
      bookName: "Becoming",
      category: "biography",
      publisher: "Crown Publishing Group",
      wantToRead: true,
      alreadyRead: false,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "1984",
      category: "literature",
      publisher: "Secker & Warburg",
      wantToRead: false,
      alreadyRead: true,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "The Alchemist",
      category: "literature",
      publisher: "HarperOne",
      wantToRead: false,
      alreadyRead: true,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "Born to Run",
      category: "fitness",
      publisher: "Alfred A. Knopf",
      wantToRead: false,
      alreadyRead: true,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "Atomic Habits",
      category: "self help",
      publisher: "Avery",
      wantToRead: false,
      alreadyRead: false,
      currentlyReading: true,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "To Kill a Mockingbird",
      category: "literature",
      publisher: "J. B. Lippincott & Co.",
      wantToRead: true,
      alreadyRead: false,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "The Subtle Art of Not Giving a F*ck",
      category: "self help",
      publisher: "HarperOne",
      wantToRead: true,
      alreadyRead: false,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "Sapiens: A Brief History of Humankind",
      category: "biography",
      publisher: "HarperCollins",
      wantToRead: false,
      alreadyRead: false,
      currentlyReading: true,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "Harry Potter and the Sorcerer's Stone",
      category: "literature",
      publisher: "Bloomsbury",
      wantToRead: false,
      alreadyRead: true,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "The Lean Startup",
      category: "self help",
      publisher: "Crown Publishing Group",
      wantToRead: false,
      alreadyRead: true,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
    {
      bookName: "Educated",
      category: "biography",
      publisher: "Random House",
      wantToRead: true,
      alreadyRead: false,
      currentlyReading: false,
    image: "https://marketplace.canva.com/EAFfzzUHgHc/1/0/1003w/canva-blue-modern-business-book-cover-POaWYfYxnLI.jpg"},
  ];
  